### ISSUE TITLE
Excluded from scheduled crawl

### ISSUE THREAD

**Issue by MattBlissett** [gbif/type-specimen-checklist#1]
I've excluded this dataset from the scheduled crawl using a machine tag, because the download endpoint doesn't set a Last-Modified, so it was being re-ingested every week. It's one of the largest checklist datasets, and we don't really want the extra load on the database for no useful reason.

**Comment by mdoering** [comment]
why is that not useful? It should be changing weekly and we should index it weekly then. Otherwise there is no point in scheduling the oozie job weekly

**Comment by mdoering** [comment]
we generate it even daily: https://github.com/gbif/gbif-configuration/blob/master/type-specimen-dwca-builder/prod.properties#L12

**Comment by MattBlissett** [comment]
Ah, but that doesn't seem to be deployed. I just looked at the file time of dwca-type-specimen-checklist.zip, which is 2017-06-13.

**Comment by mdoering** [comment]
probably got lost when we moved to the new cluster. Could be a weekly job also I reckon

**Comment by MattBlissett** [comment]
I've removed the tag to omit this from the scheduled crawl, since the download endpoint now does set a Last-Modified date.

The job isn't running since the move to the "new" cluster.

```
$ curl -I http://api.gbif.org/v1/occurrence/download/request/dwca-type-specimen-checklist.zip
HTTP/1.1 200 OK
Date: Thu, 14 Nov 2019 13:32:21 GMT
Content-Disposition: attachment; filename=dwca-type-specimen-checklist.zip
Last-Modified: Tue, 13 Jun 2017 16:09:59 GMT
Content-Type: application/octet-stream; qs=0.5
Content-Length: 88963299
…
```
